### ISSUE TITLE
ETC DS 5v

### ISSUE THREAD

**Issue by turboedge** [DStageGarage/ElectronicThrottleController#1]
If you are trying to align the connections with a DRV8825 then the 5v inputs should be on pins 5-6 not 4-5, though I don't see where they are used for anything, so I suppose it does not matter.

**Comment by DStageGarage** [comment]
Yes, you are correct, I missed it but as you said it's not used for anything and shorting pin 4 to 5 and 6 on DSpeed won't hurt either. For a second I was thinking about using this 5V but decided against it to not strain the linear regulator on DSpeed and to perhaps have a less noisy system / better signal integrity.
